name: bento

services:
  redis:
    hostname: ${REDIS_HOST:-redis}
    image: ${REDIS_IMG:-redis:7.2.5-alpine3.19}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    hostname: ${POSTGRES_HOST:-postgres}
    image: ${POSTGRES_IMG:-postgres:16.3-bullseye}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taskdb}
      POSTGRES_USER: ${POSTGRES_USER:-worker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    expose:
      - '${POSTGRES_PORT:-5432}'
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT:-5432}

  minio:
    hostname: ${MINIO_HOST:-minio}
    image: ${MINIO_IMG:-minio/minio:RELEASE.2024-05-28T17-19-04Z}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASS:-password}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET:-workflow}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: ${GRAFANA_IMG:-grafana/grafana:11.0.0}
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=WARN
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-taskdb}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-worker}
      - POSTGRES_PASS=${POSTGRES_PASSWORD:-password}
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - ./dockerfiles/grafana:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
      - broker-data:/db
    depends_on:
      - postgres
      - redis
      - minio


  exec_agent:
    image: agent
    runtime: nvidia
    restart: always
    depends_on:
      - postgres
      - redis
      - minio

    build:
      context: .
      dockerfile: dockerfiles/agent.dockerfile
      # NOTE: we build a single image for all agents so specify the GPU flags here
      # TODO: can we clean this up / make it more logical?
      args:
        NVCC_APPEND_FLAGS: "--gpu-architecture=compute_86 --gpu-code=compute_86,sm_86 --generate-code arch=compute_86,code=sm_86"
        CUDA_OPT_LEVEL: 1

    mem_limit: 4G
    cpus: 4

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
      REDIS_URL: redis://${REDIS_HOST:-redis}:6379
      S3_URL: http://${MINIO_HOST:-minio}:9000
      S3_BUCKET: ${MINIO_BUCKET:-workflow}
      # TODO: create a lower perm user on startup of minio to use for agents
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1
      RISC0_KECCAK_PO2: ${RISC0_KECCAK_PO2:-17}
      # Enable / disable along with gpu_*_agent*
      # JOIN_STREAM: 1
      # COPROC_STREAM: 1

    entrypoint: /app/agent -t exec --segment-po2 ${SEGMENT_SIZE:-21}

  aux_agent:
    image: agent
    runtime: nvidia
    pull_policy: never
    restart: always
    depends_on:
      - postgres
      - redis
      - minio

    mem_limit: 256M
    cpus: 1

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
      REDIS_URL: redis://${REDIS_HOST:-redis}:6379
      S3_URL: http://${MINIO_HOST:-minio}:9000
      S3_BUCKET: ${MINIO_BUCKET:-workflow}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1

    # NOTE: if adding more aux workers, only one needs --monitor-requeue (for task reaping)
    entrypoint: /app/agent -t aux --monitor-requeue

  gpu_prove_agent0: &gpu
    image: agent
    runtime: nvidia
    pull_policy: never
    restart: always
    depends_on:
      - postgres
      - redis
      - minio

    mem_limit: 4G
    cpus: 4

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
      REDIS_URL: redis://${REDIS_HOST:-redis}:6379
      S3_URL: http://${MINIO_HOST:-minio}:9000
      S3_BUCKET: ${MINIO_BUCKET:-workflow}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1

    entrypoint: /app/agent -t prove

    # comment-out if running in CPU proving mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # TODO: how to scale this with N gpus?
              device_ids: ['0']
              capabilities: [gpu]

  # gpu_prove_agent1:
  #   <<: *gpu

  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: ['1']
  #             capabilities: [gpu]


  # gpu_join_agent0:
  #   <<: *gpu
  #   mem_limit: 2G
  #   cpus: 2
  #   entrypoint: /app/agent -t join

  # gpu_coproc_agent0:
  #   <<: *gpu
  #   mem_limit: 2G
  #   cpus: 2
  #   entrypoint: /app/agent -t coproc


  snark_agent:
    image: agent
    runtime: nvidia

    pull_policy: never

    restart: always

    depends_on:
      - postgres
      - redis
      - minio

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
      REDIS_URL: redis://${REDIS_HOST:-redis}:6379
      S3_URL: http://${MINIO_HOST:-minio}:9000
      S3_BUCKET: ${MINIO_BUCKET:-workflow}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1

    entrypoint: /app/agent -t snark

    ulimits:
      # Needed for stark_verify bin
      # TODO: this number was just guess and check found
      stack: 90000000

  rest_api:
    restart: always
    depends_on:
      - postgres
      - minio

    build:
      context: .
      dockerfile: dockerfiles/rest_api.dockerfile

    mem_limit: 1G
    cpus: 1

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
      S3_URL: http://${MINIO_HOST:-minio}:9000
      S3_BUCKET: ${MINIO_BUCKET:-workflow}
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1

    ports:
      - '8081:8081'

    entrypoint: /app/rest_api --bind-addr 0.0.0.0:8081

  broker:
    restart: always
    depends_on:
      - rest_api

    profiles: [broker]

    build:
      context: .
      dockerfile: dockerfiles/broker.dockerfile

    mem_limit: 2G
    cpus: 2

    volumes:
      - type: bind
        source: ./broker.toml
        target: /app/broker.toml
      - broker-data:/db/
      # uncomment for local testing of broker in compose
      # - type: bind
      #   source: ./target/
      #   target: /target/

    network_mode: host

    environment:
      RUST_LOG: ${RUST_LOG:-info,broker=debug,boundless_market=debug}
      # RUST_BACKTRACE: 1
      PRIVATE_KEY: ${PRIVATE_KEY}
      RPC_URL: ${RPC_URL}
      ORDER_STREAM_URL:

    entrypoint: /app/broker --db-url 'sqlite:///db/broker.db' --set-verifier-address ${SET_VERIFIER_ADDRESS} --boundless-market-address ${BOUNDLESS_MARKET_ADDRESS} --config-file /app/broker.toml --bento-api-url http://localhost:8081

volumes:
  redis-data:
  postgres-data:
  minio-data:
  grafana-data:
  broker-data:
