[package]
name = "boundless-povw-log-updater"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
alloy-primitives = { version = "1.0", features = ["serde", "k256"] }
alloy-sol-types = "1.0"
anyhow = "1.0"
borsh = { version = "1.5", default-features = false, features = ["std", "derive"] } # TODO(povw): remove derive feature
# TODO(povw): Use a released verion of risc0 here.
risc0-povw = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates" }
risc0-povw-guests = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates", default-features = false, features = ["std", "unstable"] }
ruint = { version = "1.15", default-features = false, features = ["borsh", "std"] }
serde = "1" # TODO(povw): Remove this dep

[patch.crates-io]
# enable RISC Zero's precompiles
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }
