[package]
name = "boundless-povw-guests"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
alloy-contract = { version = "1.0", optional = true }
alloy-primitives = { version = "1.0", features = ["serde", "k256"] }
alloy-provider = { version = "1.0", optional = true }
alloy-signer = { version = "1.0", optional = true }
alloy-sol-types = "1.0"
anyhow = "1.0"
borsh = { version = "1.5", default-features = false, features = ["std", "derive"] }
postcard = { version = "1.1", features = ["alloc"] }
risc0-povw = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates" }
risc0-povw-guests = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates" }
risc0-steel = { git = "https://github.com/risc0/risc0-ethereum", branch = "victor/patch-jul18" }
ruint = { version = "1.15", default-features = false, features = ["borsh", "std"] }
serde = "1"

[dev-dependencies]
alloy = { workspace = true, features = ["network", "node-bindings", "rpc-types", "providers", "transports", "sol-types", "contract", "signers", "signer-local"] }
anyhow = { workspace = true }
bytemuck = "1.23"
rand = "0.9"
risc0-ethereum-contracts = { workspace = true, features = ["unstable"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "victor/povw-circuit-updates", default-features = false, features = ["client", "unstable"] }
tokio = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true, features = ["unstable"], optional = true }
risc0-build-ethereum = { workspace = true, optional = true }

[package.metadata.risc0]
methods = ["mint-calculator", "log-updater"]

[package.metadata.release]
release = false

[features]
default = ["build-guest", "host"]
host = ["signer", "risc0-steel/host", "dep:alloy-provider", "dep:alloy-contract"]
signer = ["dep:alloy-signer"]
build-guest = [
  "dep:risc0-build",
  "dep:risc0-build-ethereum",
]
