[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["../../lib", "../../contracts/src"]
script = "contracts/scripts"
test = "contracts/test"
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
