name: Contracts

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  contracts-changed:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      foundry: ${{ steps.changes.outputs.foundry }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          filters: |
            src:
              - 'contracts/src/**'
            foundry:
              - 'foundry.toml'
            test:
              - 'contracts/test/**'

  gas-snapshots-check:
    runs-on: [self-hosted, Linux, X64, prod, cpu]
    needs: contracts-changed
    if: ${{ needs.contracts-changed.outputs.src == 'true' || needs.contracts-changed.outputs.foundry == 'true' }}
    steps:
      - name: install npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: print forge version
        run: forge --version

      - name: Ensure gas snapshots have been updated. Reminder to run `forge test --isolate`.
        run: FORGE_SNAPSHOT_CHECK=true forge test --isolate

  upgradability:
    runs-on: [self-hosted, Linux, X64, prod, cpu]
    needs: contracts-changed
    if: ${{ needs.contracts-changed.outputs.src == 'true' || needs.contracts-changed.outputs.foundry == 'true' }}
    steps:
      - name: install npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install @openzeppelin/upgrades-core@1.41.0
        run: npm install -g @openzeppelin/upgrades-core@1.41.0

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Forge build on main branch
        run: forge build

      - name: Upload build-info artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: contracts/out/build-info/

      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download build-info artifact
        uses: actions/download-artifact@v4
        with:
          name: build-info
          path: contracts/reference-contract/build-info-reference

      - name: Run forge test on reference-contract profile
        run: forge test
        env:
          FOUNDRY_PROFILE: reference-contract
